import crypto from "k6/crypto";
import encoding from "k6/encoding";

export const DEFAULT_USER_ID = "f412f236-4edc-47a2-8f54-8763a6ed2ce8";
export const DEFAULT_TRADE_ID = "9c967550-357f-4bfb-9726-c8b863e968ce";
export const DEFAULT_SESSION_ID = "4f39c2ea-8687-41f7-85a0-1fafd3e976df";
export const JWT_SECRET =
  __ENV.JWT_SECRET ||
  "97791d4db2aa5f689c3cc39356ce35762f0a73aa70923039d8ef72a2840a1b02";

export function createToken(userId) {
  const now = Math.floor(Date.now() / 1000);
  const header = base64Url(JSON.stringify({ alg: "HS256", typ: "JWT" }));
  const payload = base64Url(
    JSON.stringify({
      sub: userId,
      iat: now,
      exp: now + 3600,
      role: "trader"
    })
  );
  const signature = crypto.hmac("sha256", JWT_SECRET, `${header}.${payload}`, "base64");
  return `${header}.${payload}.${toBase64Url(signature)}`;
}

export function createTrade(index, userId, sessionIds) {
  const entryAt = new Date(Date.UTC(2025, 2, 1, 14, 0, index));
  const exitAt = new Date(entryAt.getTime() + 60_000);
  const direction = index % 2 === 0 ? "long" : "short";
  const entryPrice = 100 + (index % 25);
  const exitPrice = direction === "long" ? entryPrice + 0.25 : entryPrice - 0.25;

  return {
    tradeId: uuid(),
    userId,
    sessionId: sessionIds[index % sessionIds.length],
    asset: "AAPL",
    assetClass: "equity",
    direction,
    entryPrice,
    exitPrice,
    quantity: 1,
    entryAt: entryAt.toISOString(),
    exitAt: exitAt.toISOString(),
    status: "closed",
    planAdherence: 4,
    emotionalState: index % 5 === 0 ? "anxious" : "calm",
    entryRationale: "Automated load test trade."
  };
}

export function htmlReport(data, title) {
  const metrics = data.metrics;
  const checksRate = metric(metrics.checks, "rate");
  const requestCount = metric(metrics.http_reqs, "count");
  const failureRate = metric(metrics.http_req_failed, "rate");
  const p95 = metric(metrics.http_req_duration, "p(95)");
  const p99 = metric(metrics.http_req_duration, "p(99)");
  const avg = metric(metrics.http_req_duration, "avg");
  const vusMax = metric(metrics.vus_max, "max");
  const thresholds = Object.entries(data.root_group?.checks || {});

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 32px; color: #17202a; }
    h1 { margin-bottom: 4px; }
    .muted { color: #5d6d7e; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; margin: 24px 0; }
    .card { border: 1px solid #d5d8dc; border-radius: 8px; padding: 16px; }
    .value { font-size: 28px; font-weight: 700; margin-top: 8px; }
    table { width: 100%; border-collapse: collapse; margin-top: 24px; }
    th, td { text-align: left; border-bottom: 1px solid #d5d8dc; padding: 10px; }
    .pass { color: #117a37; font-weight: 700; }
    .fail { color: #b03a2e; font-weight: 700; }
    pre { background: #f4f6f7; padding: 16px; overflow: auto; }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <p class="muted">Generated by k6 handleSummary at ${new Date().toISOString()}</p>
  <div class="grid">
    ${card("HTTP Requests", requestCount)}
    ${card("Failure Rate", `${formatPercent(failureRate)}`)}
    ${card("Checks Rate", `${formatPercent(checksRate)}`)}
    ${card("p95 Latency", `${formatNumber(p95)} ms`)}
    ${card("p99 Latency", `${formatNumber(p99)} ms`)}
    ${card("Average Latency", `${formatNumber(avg)} ms`)}
    ${card("Max VUs", vusMax)}
  </div>
  <h2>Thresholds</h2>
  <table>
    <thead><tr><th>Metric</th><th>Threshold</th><th>Status</th></tr></thead>
    <tbody>
      ${Object.entries(data.metrics)
        .flatMap(([name, value]) =>
          Object.entries(value.thresholds || {}).map(([threshold, result]) =>
            `<tr><td>${escapeHtml(name)}</td><td>${escapeHtml(threshold)}</td><td class="${result.ok ? "pass" : "fail"}">${result.ok ? "PASS" : "FAIL"}</td></tr>`
          )
        )
        .join("")}
    </tbody>
  </table>
  <h2>Summary JSON</h2>
  <pre>${escapeHtml(JSON.stringify({
    state: data.state,
    metrics: {
      http_reqs: metrics.http_reqs,
      http_req_failed: metrics.http_req_failed,
      http_req_duration: metrics.http_req_duration,
      checks: metrics.checks,
      vus_max: metrics.vus_max
    },
    checks: thresholds
  }, null, 2))}</pre>
</body>
</html>`;
}

export function uuid() {
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (char) => {
    const value = Math.floor(Math.random() * 16);
    const nibble = char === "x" ? value : (value & 0x3) | 0x8;
    return nibble.toString(16);
  });
}

function base64Url(value) {
  return encoding.b64encode(value, "rawurl");
}

function toBase64Url(value) {
  return value.replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_");
}

function metric(source, name) {
  return source?.values?.[name] ?? 0;
}

function card(label, value) {
  return `<div class="card"><div class="muted">${escapeHtml(label)}</div><div class="value">${escapeHtml(String(value))}</div></div>`;
}

function formatNumber(value) {
  return Number(value).toFixed(2);
}

function formatPercent(value) {
  return `${(Number(value) * 100).toFixed(2)}%`;
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
